FROM node:18

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the backend code
COPY . .

# Copy the .env file
COPY .env .env

# Expose the port your backend runs on
EXPOSE 3000

# Command to run the backend
CMD ["npm", "start"]